version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'ops_postgres:12.4'
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - 'CORD_POSTGRES_USER=ChuckNorris'
      - 'CORD_POSTGRES_DB=radical_db'
      - 'POSTGRES_HOST='
      - 'POSTGRES_PORT=5432'
      - 'POSTGRES_DB='
      - 'POSTGRES_USER='
      - 'POSTGRES_PASSWORD=r4dicalAF'
    command:
      [
        'postgres',
        '-c',
        'max_connections=5000',
        '-c',
        'fsync=off',
        '-c',
        'synchronous_commit=off',
        '-c',
        'full_page_writes=off',
      ]
  redis:
    image: 'redis:6.0.5-alpine'
    ports:
      - '127.0.0.1:6379:6379'
